version: '3'
services:

  php:
    image: php:7-apache
    container_name: lamp_php7_apache
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
    networks:
      - lamp-template

  db:
    image: mariadb:latest
    container_name: lamp_mariadb
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      # - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - lamp-template

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lamp_phpmyadmin
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lamp-template

networks:
  lamp-template:
    driver: bridge